<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4fbda2b7-f504-474b-86d4-3b8c3fd8f5fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomePal.Application\HomePal.Application.csproj" />
    <ProjectReference Include="..\HomePal.Persistence\HomePal.Persistence.csproj" />
    <ProjectReference Include="..\HomePal.Infrastructure\HomePal.Infrastructure.csproj" />
  </ItemGroup>

</Project>
